import Foundation

// MARK: - SessionOutcome

/// The recorded outcome of a completed agent session, used by
/// the AdaptivePlanner to learn from past performance.
///
/// Outcomes are persisted alongside session records and aggregated
/// to inform future planning strategies.
///
/// Reference: CLAUDE.md §30 Phase 10
public struct SessionOutcome: Sendable, Codable, Equatable {
    /// The session that produced this outcome.
    public let sessionId: String
    /// The user's original intent.
    public let intent: String
    /// Whether the session completed successfully.
    public let succeeded: Bool
    /// Number of steps actually executed.
    public let stepsUsed: Int
    /// Number of steps originally planned.
    public let stepsPlanned: Int
    /// Number of tool invocations that returned errors.
    public let toolFailures: Int
    /// Total cost in USD for this session.
    public let totalCost: Double
    /// Wall-clock duration of the session.
    public let duration: TimeInterval

    public init(
        sessionId: String,
        intent: String,
        succeeded: Bool,
        stepsUsed: Int,
        stepsPlanned: Int,
        toolFailures: Int,
        totalCost: Double,
        duration: TimeInterval
    ) {
        self.sessionId = sessionId
        self.intent = intent
        self.succeeded = succeeded
        self.stepsUsed = stepsUsed
        self.stepsPlanned = stepsPlanned
        self.toolFailures = toolFailures
        self.totalCost = totalCost
        self.duration = duration
    }

    /// Whether the session overran its planned step count.
    public var overran: Bool { stepsUsed > stepsPlanned }

    /// Efficiency ratio: steps planned / steps used. > 1.0 means underestimated.
    public var efficiency: Double {
        guard stepsPlanned > 0 else { return 0.0 }
        return Double(stepsUsed) / Double(stepsPlanned)
    }

    /// Tool failure rate (0.0-1.0).
    public var failureRate: Double {
        guard stepsUsed > 0 else { return 0.0 }
        return Double(toolFailures) / Double(stepsUsed)
    }
}

// MARK: - PlanningStrategy

/// A strategy recommendation generated by the AdaptivePlanner based on
/// historical session outcomes.
///
/// The strategy adjusts planning parameters (step count, model choice,
/// tool preferences) to improve future session outcomes.
public struct PlanningStrategy: Sendable {
    /// Suggested maximum step count for this type of task.
    public let suggestedMaxSteps: Int
    /// Suggested model override, or nil to use the default.
    public let suggestedModel: String?
    /// Tools that performed well for similar tasks.
    public let preferredTools: [String]
    /// Tool or command patterns that frequently failed and should be avoided.
    public let avoidPatterns: [String]
    /// Confidence in this strategy (0.0-1.0), based on how many
    /// matching historical sessions were found.
    public let confidence: Double
    /// Human-readable explanation of why this strategy was chosen.
    public let rationale: String

    public init(
        suggestedMaxSteps: Int = 40,
        suggestedModel: String? = nil,
        preferredTools: [String] = [],
        avoidPatterns: [String] = [],
        confidence: Double = 0.0,
        rationale: String = "Default strategy (no historical data)"
    ) {
        self.suggestedMaxSteps = suggestedMaxSteps
        self.suggestedModel = suggestedModel
        self.preferredTools = preferredTools
        self.avoidPatterns = avoidPatterns
        self.confidence = confidence
        self.rationale = rationale
    }

    /// The default strategy when no history is available.
    public static let `default` = PlanningStrategy()
}

// MARK: - AdaptivePlanner

/// A planner that learns from past session outcomes to improve
/// future planning strategies.
///
/// The adaptive planner analyzes historical sessions with similar
/// intents, adjusts step counts based on observed over/underruns,
/// identifies tools that frequently fail, and generates a strategy
/// with confidence scores.
///
/// Reference: CLAUDE.md §30 Phase 10
public struct AdaptivePlanner: Sendable {

    /// Minimum number of historical sessions needed for meaningful adaptation.
    public static let minHistoryForAdaptation = 3

    /// Maximum number of past outcomes to consider per query.
    public static let maxHistoryWindow = 50

    /// Minimum similarity score (0.0-1.0) for an intent to be considered "related".
    public static let minSimilarity = 0.2

    public init() {}

    /// Generate a planning strategy informed by past session outcomes.
    ///
    /// - Parameters:
    ///   - intent: The current user intent to plan for.
    ///   - pastSessions: Historical session records.
    ///   - pastOutcomes: Recorded outcomes for those sessions.
    /// - Returns: A PlanningStrategy with adjusted parameters.
    public func adjustStrategy(
        intent: String,
        pastSessions: [SessionRecord],
        pastOutcomes: [SessionOutcome]
    ) -> PlanningStrategy {
        // Find related past outcomes by intent similarity
        let relatedOutcomes = findRelated(
            intent: intent,
            outcomes: pastOutcomes
        )

        // Not enough data — return default
        guard relatedOutcomes.count >= Self.minHistoryForAdaptation else {
            return PlanningStrategy(
                suggestedMaxSteps: 40,
                confidence: 0.0,
                rationale: "Insufficient history (\(relatedOutcomes.count) related sessions found, need \(Self.minHistoryForAdaptation))"
            )
        }

        // Compute adjusted step count from historical data
        let suggestedSteps = computeSuggestedSteps(outcomes: relatedOutcomes)

        // Identify tools that frequently fail
        let avoidPatterns = identifyFailingPatterns(
            outcomes: relatedOutcomes,
            sessions: pastSessions
        )

        // Identify tools used in successful sessions
        let preferredTools = identifyPreferredTools(
            outcomes: relatedOutcomes,
            sessions: pastSessions
        )

        // Suggest a model if some tasks consistently need more capability
        let suggestedModel = suggestModel(outcomes: relatedOutcomes)

        // Compute confidence based on data quality
        let confidence = computeConfidence(relatedOutcomes: relatedOutcomes)

        // Build rationale
        let rationale = buildRationale(
            relatedCount: relatedOutcomes.count,
            successRate: Double(relatedOutcomes.filter(\.succeeded).count) / Double(relatedOutcomes.count),
            suggestedSteps: suggestedSteps,
            avoidPatterns: avoidPatterns
        )

        return PlanningStrategy(
            suggestedMaxSteps: suggestedSteps,
            suggestedModel: suggestedModel,
            preferredTools: preferredTools,
            avoidPatterns: avoidPatterns,
            confidence: confidence,
            rationale: rationale
        )
    }

    // MARK: - Internal

    /// Find outcomes related to the current intent using keyword overlap.
    private func findRelated(
        intent: String,
        outcomes: [SessionOutcome]
    ) -> [SessionOutcome] {
        let intentTerms = tokenize(intent)
        guard !intentTerms.isEmpty else { return [] }

        var scored: [(outcome: SessionOutcome, similarity: Double)] = []

        for outcome in outcomes.prefix(Self.maxHistoryWindow) {
            let outcomeTerms = tokenize(outcome.intent)
            guard !outcomeTerms.isEmpty else { continue }

            let intersection = intentTerms.intersection(outcomeTerms)
            let union = intentTerms.union(outcomeTerms)
            let similarity = union.isEmpty ? 0.0 : Double(intersection.count) / Double(union.count)

            if similarity >= Self.minSimilarity {
                scored.append((outcome, similarity))
            }
        }

        return scored
            .sorted { $0.similarity > $1.similarity }
            .map(\.outcome)
    }

    /// Compute a suggested step count based on historical step usage.
    private func computeSuggestedSteps(outcomes: [SessionOutcome]) -> Int {
        let stepsUsed = outcomes.map(\.stepsUsed)
        guard !stepsUsed.isEmpty else { return 40 }

        // Use the 75th percentile of actual steps used, with 25% headroom
        let sorted = stepsUsed.sorted()
        let p75Index = min(sorted.count - 1, Int(Double(sorted.count) * 0.75))
        let p75Steps = sorted[p75Index]

        let suggested = Int(Double(p75Steps) * 1.25)
        return max(5, min(100, suggested))
    }

    /// Identify tools or patterns that frequently fail.
    private func identifyFailingPatterns(
        outcomes: [SessionOutcome],
        sessions: [SessionRecord]
    ) -> [String] {
        // Collect tools from sessions with high failure rates
        let failedOutcomes = outcomes.filter { $0.failureRate > 0.3 }
        guard !failedOutcomes.isEmpty else { return [] }

        // Return session intents as patterns to avoid (simplified;
        // in production this would analyze tool-level failure data)
        let failedIntentTerms = failedOutcomes.flatMap { outcome in
            tokenize(outcome.intent)
        }

        // Find the most common terms in failed sessions
        var termCounts: [String: Int] = [:]
        for term in failedIntentTerms {
            termCounts[term, default: 0] += 1
        }

        return termCounts
            .filter { $0.value >= 2 }
            .sorted { $0.value > $1.value }
            .prefix(5)
            .map(\.key)
    }

    /// Identify tools that are commonly used in successful sessions.
    private func identifyPreferredTools(
        outcomes: [SessionOutcome],
        sessions: [SessionRecord]
    ) -> [String] {
        let successfulIds = Set(
            outcomes.filter(\.succeeded).map(\.sessionId)
        )

        // Match session records to successful outcomes and extract model info
        // (In a full implementation, we'd extract tool lists from events)
        let successfulSessions = sessions.filter {
            successfulIds.contains($0.sessionId.value)
        }

        // Return unique models used in successful sessions as a proxy
        // (the real implementation would return actual tool names from events)
        let models = Set(successfulSessions.map(\.model))
        return Array(models).sorted()
    }

    /// Suggest a model if tasks tend to need high capability.
    private func suggestModel(outcomes: [SessionOutcome]) -> String? {
        let avgSteps = outcomes.isEmpty ? 0 :
            outcomes.map(\.stepsUsed).reduce(0, +) / outcomes.count
        let successRate = outcomes.isEmpty ? 0.0 :
            Double(outcomes.filter(\.succeeded).count) / Double(outcomes.count)

        // If tasks are complex (many steps) and success rate is low,
        // suggest a more capable model
        if avgSteps > 20 && successRate < 0.5 {
            return "claude-opus-4-7"
        }

        return nil
    }

    /// Compute confidence based on data quantity and quality.
    private func computeConfidence(relatedOutcomes: [SessionOutcome]) -> Double {
        // More data = more confidence (caps at 1.0)
        let dataScore = min(1.0, Double(relatedOutcomes.count) / 10.0)

        // Higher success rate = more reliable data
        let successRate = relatedOutcomes.isEmpty ? 0.0 :
            Double(relatedOutcomes.filter(\.succeeded).count) / Double(relatedOutcomes.count)

        // Consistency of step counts (low variance = higher confidence)
        let stepsUsed = relatedOutcomes.map { Double($0.stepsUsed) }
        let variance = Self.computeVariance(stepsUsed)
        let consistencyScore = max(0.0, 1.0 - variance / 100.0)

        return (dataScore * 0.4 + successRate * 0.3 + consistencyScore * 0.3)
    }

    private static func computeVariance(_ values: [Double]) -> Double {
        guard values.count > 1 else { return 0.0 }
        let mean = values.reduce(0.0, +) / Double(values.count)
        let sumSquares = values.map { ($0 - mean) * ($0 - mean) }.reduce(0.0, +)
        return sumSquares / Double(values.count - 1)
    }

    private func buildRationale(
        relatedCount: Int,
        successRate: Double,
        suggestedSteps: Int,
        avoidPatterns: [String]
    ) -> String {
        var parts: [String] = []
        parts.append("Based on \(relatedCount) related session(s)")
        parts.append(String(format: "%.0f%% success rate", successRate * 100))
        parts.append("suggested \(suggestedSteps) max steps")

        if !avoidPatterns.isEmpty {
            parts.append("avoiding patterns: \(avoidPatterns.joined(separator: ", "))")
        }

        return parts.joined(separator: "; ")
    }

    private func tokenize(_ text: String) -> Set<String> {
        let lower = text.lowercased()
        let tokens = lower.components(separatedBy: CharacterSet.alphanumerics.inverted)
            .filter { $0.count >= 2 }
        return Set(tokens)
    }
}
