import Foundation

// MARK: - MemorySection

/// A parsed section from a project memory markdown file.
public struct MemorySection: Sendable, Equatable {
    /// The section title (from the markdown heading).
    public let title: String
    /// The content of the section (everything between this heading and the next).
    public let content: String
    /// Whether this section appears to be user-written (vs. auto-generated by the agent).
    public let isUserWritten: Bool

    public init(title: String, content: String, isUserWritten: Bool) {
        self.title = title
        self.content = content
        self.isUserWritten = isUserWritten
    }
}

// MARK: - ProjectMemory

/// Project-level persistent memory, parsed from `.zyquo/memory/project.md`.
///
/// Project memory is SACRED: Zyquo never overwrites it, only proposes patches
/// via the diff workflow. User-written sections rank higher than agent-written
/// sections in context assembly.
///
/// Reference: CLAUDE.md S23.5
public struct ProjectMemory: Sendable, Equatable {
    /// The raw markdown content.
    public let content: String
    /// Parsed sections from the markdown file.
    public let sections: [MemorySection]

    public init(content: String) {
        self.content = content
        self.sections = Self.parseSections(from: content)
    }

    /// Look up a section by its title (case-insensitive).
    ///
    /// - Parameter name: The section title to search for.
    /// - Returns: The section content, or nil if not found.
    public func section(named name: String) -> String? {
        let lower = name.lowercased()
        return sections.first { $0.title.lowercased() == lower }?.content
    }

    /// An empty project memory (no content).
    public static let empty = ProjectMemory(content: "")

    // MARK: - Parsing

    /// Parse markdown content into sections delimited by headings.
    private static func parseSections(from content: String) -> [MemorySection] {
        guard !content.isEmpty else { return [] }

        let lines = content.components(separatedBy: "\n")
        var sections: [MemorySection] = []
        var currentTitle: String?
        var currentLines: [String] = []

        for line in lines {
            if let heading = extractHeading(from: line) {
                // Flush the previous section
                if let title = currentTitle {
                    let body = currentLines.joined(separator: "\n").trimmingCharacters(in: .whitespacesAndNewlines)
                    let isUserWritten = !containsAutoGeneratedMarker(body)
                    sections.append(MemorySection(title: title, content: body, isUserWritten: isUserWritten))
                }
                currentTitle = heading
                currentLines = []
            } else {
                currentLines.append(line)
            }
        }

        // Flush the last section
        if let title = currentTitle {
            let body = currentLines.joined(separator: "\n").trimmingCharacters(in: .whitespacesAndNewlines)
            let isUserWritten = !containsAutoGeneratedMarker(body)
            sections.append(MemorySection(title: title, content: body, isUserWritten: isUserWritten))
        }

        return sections
    }

    /// Extract a heading title from a markdown heading line (# through ###).
    private static func extractHeading(from line: String) -> String? {
        let trimmed = line.trimmingCharacters(in: .whitespaces)
        guard trimmed.hasPrefix("#") else { return nil }

        // Match 1-3 # followed by a space
        var hashCount = 0
        for char in trimmed {
            if char == "#" {
                hashCount += 1
            } else {
                break
            }
        }

        guard hashCount >= 1, hashCount <= 6 else { return nil }
        let afterHashes = trimmed.dropFirst(hashCount)
        guard afterHashes.hasPrefix(" ") || afterHashes.isEmpty else { return nil }

        let title = afterHashes.trimmingCharacters(in: .whitespaces)
        return title.isEmpty ? nil : title
    }

    /// Check if the body contains markers indicating it was auto-generated.
    private static func containsAutoGeneratedMarker(_ body: String) -> Bool {
        let lower = body.lowercased()
        return lower.contains("auto-generated")
            || lower.contains("auto generated")
            || lower.contains("<!-- generated by zyquo")
    }
}
